theme: jekyll-theme-cayman
title: [GIVE&#58 Build your own genome browser]
description: Genomic Interaction Visualization Engine
navbar-links:
  Tutorial: "https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/tree/master/tutorials"
  Manual: "https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/blob/master/manuals/index.md"
