theme: jekyll-theme-cayman
title: [GIVE&#58 Build your own genome browser]
footer-links:
  GIVE Tutorial: "https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/tree/master/tutorials"
